version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    AWS_ACCOUNT_ID: "482240068519"
    IMAGE_REPO_NAME: "ci.cd.testrepo"
    IMAGE_TAG: "latest"
    IMAGE_URI: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    
phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
   commands:
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo $IMAGE_URI
      - echo IMAGE_URI
      - echo $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo IMAGE_REPO_NAME:IMAGE_TAG

  post_build:
    commands:
      - echo Build started on `date`
      - printf '[{"name":"webApi", "imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.WebApi.json
  
artifacts:
  files:
    - imagedefinitions.WebApi.json
      
